PAUSE_SECONDS_BETWEEN_MESSAGES = 0.7
EMAIL_NODE_SIZE = 3000  # Symbols of Email text per message
INITIAL_FETCH_EMAILS_COUNT = 50
EMAIL_CONNECTIONS_ATTEMPTS_COUNT = 10
EMAIL_BROADCASTER_CONNECTIONS_ATTEMPTS_COUNT = 2
