from typing import Final

PAUSE_SECONDS_BETWEEN_MESSAGES: Final[float] = 0.7
EMAIL_NODE_SIZE: Final[int] = 3000  # Symbols of Email text per message
INITIAL_FETCH_EMAILS_COUNT: Final[int] = 25
EMAIL_CONNECTIONS_ATTEMPTS_COUNT: Final[int] = 10
EMAIL_BROADCASTER_CONNECTIONS_ATTEMPTS_COUNT: Final[int] = 2
BROADCAST_BATCH_SIZE: Final[int] = 5
CRON_SECONDS_INTERVAL: Final[int] = 10
